version: "3"
services:
  alpha:
    container_name: alpha
    image: alpha
    build: 
      context: alpha
      dockerfile: Dockerfile
    ports:
      - 5001:80
    volumes:
      - ./alpha:/var/www/html/
  beta:
    container_name: beta
    image: beta
    build: 
      context: beta
      dockerfile: Dockerfile
    ports:
      - 5002:80
    volumes:
      - ./beta:/var/www/html/
  nginx:
    image: nginx
    build:
      context: nginx/
      dockerfile: Dockerfile
    ports:
      - 5000:80
    depends_on:
      - alpha
      - beta    
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: localhost
      MYSQL_USER: root
      MYSQL_PASSWORD: test
    volumes: 
        - ./init:/docker-entrypoint-initdb.d
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  alpha:
  beta: